//CREAR ARRAY
let arr = [1,2,3,4];
//AGREGAR VALOR A UN ARRAY
arr.push(5);
//QUITAR ELEMENTO DE UN ARRAY
arr.pop();
//AGREGAR VALOR AL INICIO DE UN ARRAY
arr.unshift('Nuevo');
//QUITAR EL PRIMER VALOR DE UN ARRAY
arr.shift();
//AGREGAR ARRAY EN CUALQUIER POSICION
let arrayp = ['PERU','COLOMBIA','BOLIVIA','MEXICO'];

arrayp.splice(2,0,'CHILE','ECUADOR')



